#!/bin/sh
export CLOJURE_JAR="/home/xpyman/clojure/clojure-1.3.0/clojure-1.3.0.jar"
breakchars="(){}[],^%$#@\"\";:''|\\"
CLOJURE_DIR="/home/xpyman/clojure/clojure-1.3.0"
CLOJURE_JAR="$CLOJURE_DIR/clojure-1.3.0.jar"
if [ $# -eq 0 ]; then 
     exec rlwrap --remember -c -b "$breakchars" \
        -f "$HOME"/.clj_completions \
         java -cp "$CLOJURE_JAR" clojure.main
else
     exec java -cp "$CLOJURE_JAR" clojure.main $1 -- "$@"
fi
